### ISSUE TITLE
Call to a member function getKey() on null

### ISSUE THREAD

**Issue by mrgodhani** [GetStream/stream-laravel#39]
Getting following above error in Laravel 5.3. Any idea how to fix it?

**Comment by tbarbugli** [comment]
can you include the stack trace?

**Comment by mrgodhani** [comment]
```
[2017-01-02 03:53:30] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getKey() on null in /home/vagrant/WebAppProjects/feedbox/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/Eloquent/Utils.php:10
Stack trace:
#0 /home/vagrant/WebAppProjects/feedbox/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/Eloquent/ActivityTrait.php(69): GetStream\StreamLaravel\Eloquent\Utils::createModelReference(NULL)
#1 /home/vagrant/WebAppProjects/feedbox/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/Eloquent/ActivityTrait.php(124): FeedBox\Article->activityActor()
#2 /home/vagrant/WebAppProjects/feedbox/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/StreamLaravelManager.php(75): FeedBox\Article->createActivity()
#3 /home/vagrant/WebAppProjects/feedbox/vendor/get-stream/stream-laravel/src/GetStream/StreamLaravel/Eloquent/CreateRemoveObserver.php(8): GetStream\StreamLaravel\StreamLaravelManager->activityCreated(Object(FeedBox\Article))
#4 [internal function]: GetStream\StreamLaravel\Eloquent\CreateRemoveObserver->created(Object(FeedBox\Article))
#5 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(FeedBox\Article))
#7 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#8 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1663): Illuminate\Events\Dispatcher->fire('eloquent.create...', Array)
#9 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1591): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.create...', false)
#10 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1471): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(561): Illuminate\Database\Eloquent\Model->save()
#12 /home/vagrant/WebAppProjects/feedbox/vendor/bosnadev/repositories/src/Bosnadev/Repositories/Eloquent/Repository.php(120): Illuminate\Database\Eloquent\Model::create(Array)
#13 /home/vagrant/WebAppProjects/feedbox/app/Console/Commands/FetchArticles.php(87): Bosnadev\Repositories\Eloquent\Repository->create(Array)
#14 [internal function]: FeedBox\Console\Commands\FetchArticles->handle()
#15 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#16 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#17 /home/vagrant/WebAppProjects/feedbox/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/WebAppProjects/feedbox/vendor/symfony/console/Application.php(821): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/WebAppProjects/feedbox/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(FeedBox\Console\Commands\FetchArticles), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/WebAppProjects/feedbox/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/WebAppProjects/feedbox/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/WebAppProjects/feedbox/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}  
```

**Comment by tbarbugli** [comment]
is it possible to add the definition of the FeedBox\Article model

**Comment by mrgodhani** [comment]
That's the model I have @tbarbugli 
```
<?php

namespace FeedBox;

use GetStream\StreamLaravel\Eloquent\ActivityTrait;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use ActivityTrait;
    protected $table = 'articles';
    protected $fillable = [
        'unique_id',
        'title',
        'url',
        'domain',
        'author',
        'summary',
        'content',
        'lead_image_url',
        'date_published',
        'feed_id'
    ];

    /**
     * Belongs to Feed
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function feed() {
        return $this->belongsTo('FeedBox\Feed');
    }
}
```

**Comment by tbarbugli** [comment]
`ActivityTrait` assumes that your model has a 'user' attribute (for activity.actor). Can you look at the instructions here: https://github.com/GetStream/stream-laravel#activity-fields?

**Comment by mrgodhani** [comment]
So you mean to say it has to belong to User model ? But what if it doesn't belong to User model how do we solve it? Sorry new to this API and documentation wasn't clear enough.

**Comment by mrgodhani** [comment]
Cool thanks works.
